overrides: coala.yaml

language: ruby
language_versions:
  - 2.5.1
gitignore_language: Jekyll
gitignore_extra_rulesets:
  - GitBook
build_script: .ci/build.sh

requires:
  - https://gitlab.com/coala/mobans

configuration:
  template_dir:
    - 'mobans:templates/'
    - 'mobans:assets/'
  configuration: .moban.yaml
  configuration_dir: 'mobans:'
targets:
  - .gitignore: coala-gitignore.jj2
  - .travis.yml: ci/coala-travis.yml.jj2
