overrides: coala.yaml

language: ruby
gitignore_language: Jekyll
gitignore_extra_rulesets:
  - GitBook

requires:
  - https://gitlab.com/coala/mobans

configuration:
  template_dir:
    - 'mobans:templates/'
    - 'mobans:assets/'
  configuration: .moban.yaml
  configuration_dir: 'mobans:'
targets:
  - .gitignore: coala-gitignore.jj2
